# Generated by Django 4.2.5 on 2024-02-12 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0075_increase_resource_link_length"),
        ("submission", "0075_user_matrix_id"),
    ]

    operations = []
